### ISSUE TITLE
Deploy as a full NPM package

### ISSUE THREAD

**Issue by robhawkes** [cityjson/cityjson-threejs-loader#1]
### Description
- I'd like to install `cityjson-threejs-loader` in my own application on CodeSandbox
- Currently there is no pre-built package on NPM to install this via `npm install cityjson-threejs-loader`
- The only way to use the package (at least on CodeSandbox) is to manually copy/paste the `./src` directory and build it at runtime

### Expectation
- Package can be installed via `npm install cityjson-threejs-loader`

**Comment by liberostelios** [comment]
I think this will be available soon, as long as the API becomes a bit more stable.

For now, you can still install it via git:
```
npm i https://github.com/cityjson/cityjson-threejs-loader
```

**Comment by liberostelios** [comment]
Now released in npm registry.
