### ISSUE TITLE
How to integrate cityjson-threejs-loader with angular 14

### ISSUE THREAD

**Issue by moniruzzamanrony** [cityjson/cityjson-threejs-loader#7]
Hi, 
I'm trying to use cityjson-threejs-loader in Angular 14 app.I'm trying to add cityjson-threejs-loader  via the NPM package installer using,
`npm install git+https://github.com/cityjson/cityjson-threejs-loader.git`

your package was added to my node_modules but isn't working.
Here,
```
    const parser = new CityJSONWorkerParser();
    const loader = new CityJSONLoader(parser); //Got error:  TS2554: Expected 0 arguments, but got 1.
    loader.load("/assets/cityjsons/cube.city.json");

    this.scene.add(loader.scene);
```

Could you help me, how can I integrate cityjson-threejs-loader with angular 14.

Thanks.

**Comment by imtiazShakil** [comment]
Hi,

I've a made a pull request which fixes Angular Integration. Can you please review & merge it if possible.  @liberostelios  or @Ylannl

Thanks.

**Comment by moniruzzamanrony** [comment]
Hi,
I have seen your latest implementation for the latest Angular. That is truly amazing. Hopefully, the new release will be more convenient for Angular integration with this library.

We're waiting for a new release.
Thanks.

**Comment by liberostelios** [comment]
@imtiazShakil @moniruzzamanrony Has #8 addressed your concern? Should we close this issue?

**Comment by moniruzzamanrony** [comment]
Yeah, addressed. Thanks @liberostelios @imtiazShakil .
we should close this issue and earlier publish the latest version in the npm registry as if anyone can use it easily. Then we will also use your npm package. 

Thanks.
